Repository djx-community/encuesta, pull requests merged in 2022-10, with the labels that each got.

#18 Initial configuration and Splash screen creation
  assets/images/Quiz_Logo.webp
  lib/config/assets_path/assets_path.dart
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/modules/home_screen.dart
  lib/modules/splash_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/util/services/services.dart
  lib/util/ui/animations/animation.dart
  lib/widgets/widgets.dart
  pubspec.yaml
Labels: hacktoberfest-accepted

#19 Winning Screen completed
  .vscode/settings.json
  assets/images/Winning_Screen.png
  lib/config/assets_path/assets_path.dart
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/leader_board_screen.dart
  lib/screens/splash_screen.dart
  lib/screens/winning_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/greeting_screen_image_widget.dart
  lib/widgets/score_display_widget.dart
  pubspec.yaml
Labels: hacktoberfest-accepted

#22 Home Screen designed
  .vscode/launch.json
  .vscode/settings.json
  assets/images/home_screen.png
  flutter_01.png
  lib/config/assets_path/assets_path.dart
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/screens.dart
  lib/widgets/custom_button.dart
  lib/widgets/nav_bar.dart
  lib/widgets/user_indicator.dart
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#21 Game Loading Screen added, greeting screen widget slight tweak
  README.md
  assets/images/game_loading.png
  flutter_01.png
  lib/config/assets_path/assets_path.dart
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/game_loading_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/greeting_screen_image_widget.dart
  lib/widgets/progression_bar_widget.dart
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#23 pubspec conflict resolved
  pubspec.yaml
Labels: documentation

#25 Leader Board Completed
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/leader_board_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/point_table_widget.dart
  lib/widgets/user_profile_card_widget.dart
Labels: enhancement, hacktoberfest-accepted

#27 Hosting Screen Completed and Home Screen Design corrections
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/hosting_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/custom_button.dart
  lib/widgets/custom_buttons_widgets.dart
  lib/widgets/quiz_category_widget.dart
  lib/widgets/user_id_app_card_widget.dart
Labels: enhancement, hacktoberfest-accepted
