Repository djx-community/encuesta, pull requests merged in 2022-11, with the labels that each got.

#28 lobby list view added, review and edit needed
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/hosting_screen.dart
  lib/screens/leader_board_screen.dart
  lib/screens/lobby_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/joined_players_list_widget.dart
  lib/widgets/quiz_category_widget.dart
  lib/widgets/user_id_app_card_widget.dart
Labels: enhancement, help wanted

#29 Joined Room initial UI added
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/hosting_screen.dart
  lib/screens/joined_room_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/quiz_category_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, help wanted

#30 Social Play Screen Basic UI added
  assets/images/social_play.png
  lib/config/assets_path/assets_path.dart
  lib/config/routes/routes.dart
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/social_play_screen.dart
  lib/util/helpers/text_helpers.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, help wanted

#31 Quiz Screen Completed
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/home_screen.dart
  lib/screens/joined_room_screen.dart
  lib/screens/quiz_screen.dart
  lib/screens/splash_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/question_options_list_widget.dart
  lib/widgets/quiz_question_canvas_widget.dart
  lib/widgets/quiz_screen_head_widget.dart
  lib/widgets/quiz_timer_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#33 Host view of game screen created
  .vscode/settings.json
  lib/config/routes/routes.dart
  lib/config/themes/themes.dart
  lib/main.dart
  lib/screens/host_view_of_game_screen.dart
  lib/screens/joined_room_screen.dart
  lib/screens/quiz_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/question_options_list_widget.dart
  lib/widgets/quiz_timer_widget.dart
  lib/widgets/user_id_app_card_widget.dart
  pubspec.yaml
Labels: enhancement, hacktoberfest-accepted

#35 host view of screen tweaks and home screen layout bug fixed
  lib/screens/home_screen.dart
  lib/screens/host_view_of_game_screen.dart
  lib/screens/quiz_screen.dart
  lib/widgets/question_options_list_widget.dart
Labels: bug

#44 host room screen issues fixed
  lib/screens/hosting_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/quiz_category_widget.dart
Labels: enhancement

#47 joined room screen to fixed width, slight tweak on waiting text.
  lib/screens/joined_room_screen.dart
  lib/util/helpers/text_helpers.dart
Labels: enhancement

#48 bottom app bar design changed and naming convention error fixed
  lib/config/themes/themes.dart
  lib/screens/home_screen.dart
  lib/screens/social_play_screen.dart
  lib/util/helpers/text_helpers.dart
  lib/widgets/bottom_app_bar_widget.dart
  lib/widgets/nav_bar.dart
Labels: enhancement
